package edu.vt.EntityBeans;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serial;
import java.io.Serializable;
import java.sql.Date;

/*
The @Entity annotation designates this class as a Jakarta Persistence Entity POJO class
representing the UserArtist table in the MusicDB database.
 */
@Entity

// Name of the database table represented by this class
@Table(name = "UserArtist")

@NamedQueries({
        // This named query is used in UserArtistFacade
        @NamedQuery(name = "UserArtist.findByUserArtistName", query = "SELECT c FROM UserArtist c WHERE c.name = :name"),
        @NamedQuery(name = "UserArtist.findArtistsByUserDatabasePrimaryKey", query = "SELECT p FROM UserArtist p WHERE p.userId.id = :primaryKey"),
        @NamedQuery(name = "UserArtist.findByUserArtistSpotifyId", query = "SELECT c FROM UserArtist c WHERE c.spotify_id = :spotify_id")
})

public class UserArtist implements Serializable {
    /*
    ========================================================
    Instance variables representing the attributes (columns)
    of the UserArtist table in the MusicDB database.

    CREATE TABLE UserArtist
    (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    spotify_id VARCHAR(22) NOT NULL,
    name VARCHAR(128) NOT NULL,
    image_url VARCHAR(256) NOT NULL,
    user_id INT UNSIGNED,
    FOREIGN KEY(user_id) REFERENCES User(id) ON DELETE CASCADE
    );
    ========================================================
     */
    @Serial
    private static final long serialVersionUID = 1L;
    /*
    Primary Key id is auto generated by the system as an Integer value
    starting with 1 and incremented by 1, i.e., 1,2,3,...
    A deleted entity object's primary key number is not reused.
     */
    // id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;

    // Spotify artist id
    //spotify_id VARCHAR(22) NOT NULL
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 22)
    @Column(name = "spotify_id")
    private String spotify_id;

    // Artist name
    // name VARCHAR(128) NOT NULL
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 128)
    @Column(name = "name")
    private String name;

    // Artist Image URL
    // image_url VARCHAR(256) NOT NULL
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 256)
    @Column(name = "image_url")
    private String image_url;

    // user_id INT UNSIGNED NOT NULL,
    @JoinColumn(name = "user_id", referencedColumnName = "id")
    @ManyToOne
    private User userId;


    //===================
    // Constructor Method
    //===================

    // Used in PrepareCreate method
    public UserArtist() {
    }

    /*
     *********************************
     *   Getter and Setter Methods   *
     *********************************
     */

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSpotify_id() {
        return spotify_id;
    }

    public void setSpotify_id(String spotify_id) {
        this.spotify_id = spotify_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public User getUserId() {
        return userId;
    }

    public void setUserId(User userId) {
        this.userId = userId;
    }

    /*
     ***************************************
     *   Instance Methods Used Internally  *
     ***************************************
     */

    // Generate and return a hash code value for the object with database primary key id
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    /*
     Checks if the UserArtist object identified by 'object' is the same as the UserArtist
     object identified by 'id' Parameter object = UserArtist object identified by 'object'.
     Returns True if the UserArtist 'object' and 'id' are the same; otherwise, return False
     */
    @Override
    public boolean equals(Object object) {
        if (!(object instanceof UserArtist)) {
            return false;
        }
        UserArtist other = (UserArtist) object;
        return (this.id != null || other.id == null) && (this.id == null || this.id.equals(other.id));
    }

    // Return String representation of database primary key id
    @Override
    public String toString() {
        return id.toString();
    }
}
